### PR TITLE
fix for Grisu on Julia 1.6

### LINKED ISSUE #24: Sections using Base.Grisu need to be rewritten
As of https://github.com/JuliaLang/julia/pull/32859 `Base.Grisu` has been removed from Julia and the sections of `Showoff` that depend on Grisu will need to be rewritten, I believe.

### PR DESCRIPTION
**Pull request by KristofferC**
This needs  https://github.com/JuliaRegistries/General/pull/21688 to go through first.

Fixes #24

### CODE REVIEW

File: src/Showoff.jl [hunk 1]
```diff
@@ -4,6 +4,12 @@ module Showoff
 
 using Dates
 
+if isdefined(Base, :Grisu)
+    const Grisu = Base.Grisu
```
Comment (aviatesk) [inline src/Showoff.jl]:
```suggestion
    import Base.Grisu
```

would be better because it will import its exported variables as well ? Not sure Showoff.jl uses them though.

Comment (KristofferC) [reply src/Showoff.jl]: > because it will import its exported variables as well 

I agree this is better but what do you mean it will import exported variables? That's only when `using`, no?

Comment (aviatesk) [reply src/Showoff.jl]: > That's only when `using`, no?

aha, yes, so this actually doesn't change the meaning of this program, I guess.

**Comment by KristofferC** [comment]
Should be good to go

**Comment by timholy** [comment]
Thanks!
